AWSTemplateFormatVersion: '2010-09-09'
Description: 'Database infrastructure for manga reader - RDS PostgreSQL, Security Groups, Secrets Manager'

Parameters:
  EnvironmentName:
    Description: Environment name that will be prefixed to resource names
    Type: String
    Default: manga-reader

  DBInstanceClass:
    Description: RDS instance class
    Type: String
    Default: db.t3.micro
    AllowedValues: [db.t3.micro, db.t3.small, db.t3.medium, db.r6g.large]

  DBAllocatedStorage:
    Description: The size of the database (GB)
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 65536

  DBName:
    Description: Database name
    Type: String
    Default: mangareader

  DBUsername:
    Description: Database admin username
    Type: String
    Default: mangaadmin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'

  MultiAZ:
    Description: Multi-AZ deployment
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']

Resources:
  # Database Security Group
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${EnvironmentName}-database-sg'
      GroupDescription: Security group for RDS database
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPC-ID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
          Description: 'PostgreSQL access from Lambda functions'
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-database-sg'

  # Lambda Security Group
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${EnvironmentName}-lambda-sg'
      GroupDescription: Security group for Lambda functions
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPC-ID'
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          DestinationSecurityGroupId: !Ref DatabaseSecurityGroup
          Description: 'PostgreSQL access to database'
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: 'HTTPS access for AWS services'
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-lambda-sg'

  # Database Subnet Group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${EnvironmentName}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds:
        - Fn::ImportValue: !Sub '${EnvironmentName}-Private-Subnet-AZ1'
        - Fn::ImportValue: !Sub '${EnvironmentName}-Private-Subnet-AZ2'
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-db-subnet-group'

  # Generate random password for database
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${EnvironmentName}/database/credentials'
      Description: Database credentials for manga reader application
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # RDS Database Instance
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${EnvironmentName}-database'
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '15.4'
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}'
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      StorageEncrypted: true
      MultiAZ: !Ref MultiAZ
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      DeletionProtection: false
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RDSEnhancedMonitoringRole.Arn
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-database'

  # Store database connection info in Secrets Manager
  DatabaseConnectionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${EnvironmentName}/database/connection'
      Description: Database connection information
      SecretString: !Sub |
        {
          "host": "${DatabaseInstance.Endpoint.Address}",
          "port": ${DatabaseInstance.Endpoint.Port},
          "dbname": "${DBName}",
          "username": "${DBUsername}",
          "password": "{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}"
        }

  # IAM Role for RDS Enhanced Monitoring
  RDSEnhancedMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-rds-monitoring-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole'

Outputs:
  DatabaseEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub '${EnvironmentName}-Database-Endpoint'

  DatabasePort:
    Description: RDS instance port
    Value: !GetAtt DatabaseInstance.Endpoint.Port
    Export:
      Name: !Sub '${EnvironmentName}-Database-Port'

  DatabaseName:
    Description: Database name
    Value: !Ref DBName
    Export:
      Name: !Sub '${EnvironmentName}-Database-Name'

  DatabaseSecretArn:
    Description: Database credentials secret ARN
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${EnvironmentName}-Database-Secret-Arn'

  DatabaseConnectionSecretArn:
    Description: Database connection secret ARN
    Value: !Ref DatabaseConnectionSecret
    Export:
      Name: !Sub '${EnvironmentName}-Database-Connection-Secret-Arn'

  LambdaSecurityGroup:
    Description: Security group for Lambda functions
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-Lambda-Security-Group'

  DatabaseSecurityGroup:
    Description: Security group for database
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-Database-Security-Group'